services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

  express:
    image: hackitba-2024-backend
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${EXPRESS_PORT}:${EXPRESS_PORT}"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb
